### ISSUE TITLE
Add PyTorch notebook images for Jupyterhub

### ISSUE THREAD

**Issue by anishasthana** [opendatahub-io/odh-manifests#191]
Given the prevalence of PyTorch in industry, having a PyTorch notebook image available as one of the default options could be useful for data scientists.

**Comment by chauhankaranraj** [comment]
IMHO when experimenting with ideas, using pytorch is generally faster, more flexible, and easier to debug than tensorflow (at least tensorflow version 1.x). Also, the user support provided through the [pytorch forum](https://discuss.pytorch.org/) is really amazing. Since we're often involved in research-like projects, I think having a pytorch notebook image would be definitely be useful for the data scientists. Also fwiw, I think even some of our interns last year were doing their projects in pytorch.

**Comment by anishasthana** [comment]
@vpavlin

**Comment by vpavlin** [comment]
I have zero experience with PyTorch...are you talking just about having PyTorch pre-installed in a notebook image? Is there any support for GPU? Are there any additional packages which should be installed with PyTorch to make the experience great? (e.g. with Tensorflow, we enabled Tensorboard)

**Comment by chauhankaranraj** [comment]
> Is there any support for GPU?

Yep, PyTorch can definitely use GPU's, if that's what you're wondering :)

> Are there any additional packages which should be installed with PyTorch to make the experience great? (e.g. with Tensorflow, we enabled Tensorboard)

I think [torchvision](https://pypi.org/project/torchvision/) is a package generally installed in tandem with PyTorch. It basically has a bunch of datasets, pre-saved model architectures, and some utilities for image processing.

Also tensorboard can be used with PyTorch too ([docs here](https://pytorch.org/tutorials/recipes/recipes/tensorboard_with_pytorch.html)). Although, I'm not 100% if it's possible to integrate it into jupyter.

**Comment by harshad16** [comment]
Created a repo to address this  issue: https://github.com/thoth-station/s2i-pytorch-notebook
let figure out what all packages are required for the application.

**Comment by LaVLaS** [comment]
Closing as PyTorch is one of the default notebook options since ODH 1.5
