### ISSUE TITLE
Unable to use imagestreams from different namespaces in JupyterHub Spawner

### ISSUE THREAD

**Issue by Harshit-9398** [opendatahub-io/odh-manifests#248]
Hi,
I have been using ODH for quite some time and I have observed that the spawner menu on the Jupyterhub UI shows only the imagestreams that are present in the same openshift project as the ODH instance and that too having a label `opendatahub.io/notebook-image=true`.
I wanted to know if there's any way to have the imagestreams present in a **common openshift namespace** (having label `opendatahub.io/notebook-image=true`), which can be referenced in multiple ODH instances running in different openshift projects altogether.
@vpavlin @LaVLaS @harshad16

**Comment by Harshit-9398** [comment]
I have been able to find [this](https://github.com/opendatahub-io/jupyterhub-singleuser-profiles) repo and found this [line](https://github.com/opendatahub-io/jupyterhub-singleuser-profiles/blob/38061b9e41e1035e103a3afd4d4311415f4c9c5e/jupyterhub_singleuser_profiles/images.py#L17) where we can make changes to modify the default namespace being used to fetch the list of notebook images which are shown on the spawner page.
But we are not able to find the file/place where we can change this in JupyterHub. Can you please suggest are we on the right track and guide to where exactly this change needs to be made in ODH?

**Comment by vpavlin** [comment]
Hi @Harshit-9398! We did not consider this use case before, so this is not expected to work - ImageStreams are only loaded from the namespace where JupyterHub runs.

The issue with loading from other namespaces is that we would have to give JH serviceaccount access to those namespace which would be a manual step during installation.

Our thinking is more that in case there are multiple JupyterHub instances, those would be separate and thus each would have own list of ImageStreams.

**Comment by Harshit-9398** [comment]
Hi @vpavlin,
Yes, I do believe your approach is more feasible in general, but as per my usecase, I need to have all imagestreams present in a common namespace which can be accessed by ODH instances across different namespaces.
I checked the contents of the JupyterHub pod in ODH, but I was unable to find [this](https://github.com/opendatahub-io/jupyterhub-singleuser-profiles/blob/38061b9e41e1035e103a3afd4d4311415f4c9c5e/jupyterhub_singleuser_profiles/images.py#L17) file.
**So can you please guide me where to find the above file so that I can try to make the changes according to my requirement?**

**Comment by vpavlin** [comment]
So, the way I would approach to try this out would be to change `jupyterhub_config.py` - specifically this line: https://github.com/opendatahub-io/jupyterhub-odh/blob/master/.jupyter/jupyterhub_config.py#L209 - you can provide a `namespace=` argument for the constructor (see https://github.com/opendatahub-io/jupyterhub-singleuser-profiles/blob/master/jupyterhub_singleuser_profiles/profiles.py#L30).

Then the defined namespace would be used. The problem is that it would be used for anything in jupyterhub-singleuser-profiles library - ImageStreams lookup, but also Profiles configuration ConfigMap, so it might complicate things a bit.

If we wanted to add it as a feature, I'd say we could consider to add a config section into the jupyterhub-singleuser-profiles ConfigMap (see the current structure https://github.com/opendatahub-io/jupyterhub-singleuser-profiles#configuration) which could have something like

```
configuration:
  imagestream_namespaces:
  - my_custom_namespace
```

And then load it and pass to the `Image` class to look for images in.

WDYT?

CC @mroman-redhat

**Comment by vpavlin** [comment]
@Harshit-9398 Hey, did you spend more time on this?
