### ISSUE TITLE
Provision of vGPUs for individual users in ODH

### ISSUE THREAD

**Issue by altruistcoder** [opendatahub-io/odh-manifests#254]
Hello,

I am working on a project in which we are leveraging ODH and we have enabled the users to use GPUs to train their ML models. But, we are facing one issue yet. We are not able to provide users with the functionality of using virtual GPUs and instead when they enter the value of `GPU_COUNT` as `1` the system automatically reserves the complete GPU hardware present on that node on which the corresponding user pod is running for that individual user and all other users see the **"Insufficient GPUs"** message when they try to spawn an image keeping GPU_COUNT as 1 (assuming the cluster contains only a single GPU node with one GPU present in it). We are using the AWS EC2 machine type `g4dn.4xlarge` (which comes with 1 GPU & 16 vCPUs) in our cluster. Can you please provide us some guidance on how to use virtual GPUs in ODH, it would be really helpful for solving our purpose.

**Comment by altruistcoder** [comment]
Hello @nakfour @vpavlin,

I saw that you have identified this issue as an `enhancement`. So, can we assume that there is no particular solution for this problem **as of now** and it is not possible **yet** to use Virtual GPUs. So, if there is only one GPU node (having only 1 GPU in it), it is not possible that multiple users are able to spawn the notebook images by making GPU_COUNT as "1" simultaneously as there is no mechanism to have virtual GPUs right now in ODH.
This is my understanding till now, please do correct me if I have misunderstanding at some point.

**Comment by vpavlin** [comment]
Hi @altruistcoder, sorry for late reply. I had a bit hard time understanding your request, but your previous comments clears it up, I think.

Correct, there is no way to use a single GPU in multiple pods simultaneously currently. This is not limitation of ODH, but of Kubernetes and Nvidia drivers - since AFAIK there is not memory separation on Nvidia GPU, they do not currently allow the GPU to be used by ultiple users at the same time, since that would be a security concern.

There is some work being done for this all over the place - I believe @mmgaggle was going to provide more info on this.

If having a mapping of 1 GPU -> 1 user is an issues, we tend to recommend to use only CPUs in your notebooks and then submit a Kubernetes Job, or use Tekton Pipelines or Argo Workflows to at least get a "time sharing" where the job would free up the GPU when it finishes (unlike the notebook which holds on to GPU as long as the server is running).

Hope it helps

**Comment by altruistcoder** [comment]
Hello @vpavlin,

Thank you for sharing the fact that single GPU cannot be used simultaneously by multiple pods. knowing this, it will be helpful for me to conclude my approach for my usecase.
Now I will focus on the new approach that you have suggested, with the Kubernetes job, Tekton Pipelines or Argo Workflows. Also, Argo is already there in the ODH and Tekton in the roadmap of ODH v1.0. 

So, would it possible for you to please provide some **resources or some documentation** from where I can gain a better knowledge on proceeding with the approach you shared?

Also, I got a **blog provided by AWS which can be seen [here](https://aws.amazon.com/blogs/opensource/virtual-gpu-device-plugin-for-inference-workload-in-kubernetes/)** and was trying following through it regarding the implementation of virtual GPUs in OpenShift, so I just thought to share this with you so as to get your suggestions on whether this can be useful in some way to approach our problem or not.

**Comment by mmgaggle** [comment]
There are a number of concepts that exist in this problem space:

1. GPU time sharing - some sort of abstraction like an operating system kernel (for cpus),  that multiplexes tasks from different users on single GPU, or shared GPU collection.

2. GPU partitioning - Dividing the memory and/or cores on a GPU into partitions that can be consumed in whole by distinct users.

3. GPU squatting - pods holding GPU resources, but idling.

Instead of having a notebook pod run on a GPU instance, perhaps schedule a pytorchjob [1] /kubeflowjob jobs that run until completion. Once the job completes, the resources are made available to the cluster for other jobs. Current quotas types of "max GPUs" feel lacking, it seems a more useful unit of quota would be GPU hours, to prevent #3. I suppose an admission controller could be written to prevent pods that are not of a job variety from being scheduled when they are requesting GPU resources. This is the inverse of #3. 

NVIDIA has a a technology called MIG (multi-instance GPU), that allows the virtualization of GPUs in a way that is more or less analogous with SR-IOV network controllers (#2). These new capabilities are not yet surfaced in a way that they can be leveraged through the NVIDIA operator in kubernetes. There are startups working on these sorts of capabilities as well - run.ai being a notable example.

[1] https://www.kubeflow.org/docs/reference/pytorchjob/v1/pytorch/

**Comment by altruistcoder** [comment]
Thanks for providing all this information @mmgaggle & @vpavlin. I agree with the approach you have shared. Its better to
have a **Job/ Workflow** to run the GPU workloads instead of a pod acquiring the whole GPU and not using it for most of the time during its allocation. 

One approach that I have been able to figure out till now is using a Openshift Job to train the ml workloads and use S3 as a source for dataset and for storing the trained models. The job should run the corresponding code for training the model by accessing the dataset from S3 and storing the trained model again to S3. But, we would need to find a way to trigger this Openshift Job from the Jupyterhub environment itself alongwith how can we dynamically send the python training code to the Openshift Job.

Can you please suggest some steps or provide some guidance, documents or **some resources** on how can I proceed with the approaches you have shared such as going through with the Tekton Pipelines or Argo Workflows or Kubeflow Jobs.

**Comment by vpavlin** [comment]
Some time ago I created this to experiment with the approach: https://github.com/vpavlin/odh-tensorflow-jobs

I am not sure if it still works, but maybe it can provide some ideas.

I guess for Argo and Tekton you can find some docs on their websites and experiment. I don't have any specific links regarding those.

If you come up with something, please let us know, this would be a great addition to our tutorials or docs.

**Comment by vpavlin** [comment]
@altruistcoder Can we close this issue?
