### ISSUE TITLE
KfDef manifest links on Operator Install Page on OperatorHub are incorrect

### ISSUE THREAD

**Issue by schnn** [opendatahub-io/odh-manifests#336]
Links here are broken

<img width="893" alt="Screenshot 2021-03-02 at 11 34 11 AM" src="https://user-images.githubusercontent.com/15902873/109607823-d2d87a00-7b4e-11eb-86a3-8ef51763818e.png">

Where can we find the right manifest that includes Kubeflow and KFServing

**Comment by nakfour** [comment]
Hi @nschn yes we are aware the KF example link that includes KF Serving is broken since we pointed to Kubeflow master and that repo structure was changed. You can find it here: https://github.com/kubeflow/manifests/blob/master/distributions/kfdef/kfctl_openshift.master.kfptekton.yaml
but you have to change the uri to "https://github.com/kubeflow/manifests/archive/306d02979124bc29e48152272ddd60a59be9306c.tar.gz" the last merge before the restructuring of manifest.
