### ISSUE TITLE
Add image build automation 

### ISSUE THREAD

**Issue by rimolive** [opendatahub-io/odh-manifests#414]
**Is your feature request related to a problem? Please describe.**
Following the discussion in the [Users Mailling list](https://lists.opendatahub.io/archives/list/users@lists.opendatahub.io/thread/JCRK4ILX2GYRK5GUZEU4DOIW46G36ZFN/) we should automate image builds in order to have a place for the community to new features and bug fixes.

**Describe the solution you'd like**
Create a new repository in `opendatahub-io` organization containing the code to build all ODH-related images.

**Describe alternatives you've considered**
Add S2i build section to the docs in case users want to create their own image.

**Additional context**
N/A

**Comment by anishasthana** [comment]
@harshad16 Are there any Thoth integrations we can leverage here? This is primarily focused on actual application images, e.g., quay.io/opendatahub/trino, _not_ images for notebooks/jupyterhub themselves.

**Comment by shawnzhu** [comment]
Is this repo the right place to contribute container image build manifests (skaffold/Dockerfile etc)? I use this repo today: https://github.com/IBM/docker-prestodb but happy to follow guidance from ODH

**Comment by anishasthana** [comment]
We have a number of images in https://github.com/opendatahub-io/odh-images -- I think that would be the best location to store build manifests.

**Comment by shawnzhu** [comment]
I just create a patch to https://github.com/RedHatInsights/ubi-hive/issues/8 to reflect a common configuration when operating hive metastore in production.

I'm curious if there's any doc/practice on build/test/publish container images? I use skaffold + container-structure-test to adopt incremental build when building multiple images in a single repo, and I'm happy to learn and/or share.

**Comment by shawnzhu** [comment]
@rimolive I would propose an image build workflow managed by [skaffold](https://skaffold.dev/) and [constainer-structure-test](https://github.com/GoogleContainerTools/container-structure-test) into repo https://github.com/opendatahub-io/odh-images to build images incrementially. My breakdown:

1. manages image build workflow via [skaffold image builder](https://skaffold.dev/docs/pipeline-stages/builders/)
    - use either `Dockerfile` or custom script as builder.
    - for trusted build from origin branches instead of forked branch, it could try [in-cluster](https://skaffold.dev/docs/pipeline-stages/builders/#in-cluster-build) build if local build is slow
    - Add test cases to test built image
2. run image build workflow during CI of https://github.com/opendatahub-io/odh-images
3. Adding required images from other repo as submodule so that it could manage images dependency via code changes

I'm happy to take action for :point_up: proposal or address any comments/guidance.
