### ISSUE TITLE
TrustyAI deploys blank quarkus app

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/odh-manifests#783]
**Describe the bug**
The TrustyAI component deploys a blank quarkus app.

![image](https://user-images.githubusercontent.com/1628206/231289261-1755a648-7462-459a-87c8-0b1854fbd31d.png)

**Steps To Reproduce**
1. Deploy default kfdef for 1.5.0

**Expected behavior**

**Workaround (if any)**

**Open Data Hub Version**
1.5.0

**OpenShift Version**
Version #:  4.12
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...):

**Additional context**

**Comment by anishasthana** [comment]
@ruivieira @RobGeada

**Comment by ruivieira** [comment]
Thanks, @strangiato @anishasthana 

I think the app my not be empty, more the case of the top level default page not having been removed.
@strangiato can you `GET /q/openapi` and verify this is the case? All other endpoints should be defined.
I've opened a ticket for removing that page.

**Comment by ruivieira** [comment]
@strangiato @anishasthana Fixed in https://github.com/trustyai-explainability/trustyai-explainability/pull/143. Since a landing page is not supported, `GET /` will now return a 404 page with a list of available endpoints.

<img width="543" alt="image" src="https://user-images.githubusercontent.com/327909/231981072-ca8bd4ed-a002-470f-8f69-08444cd81ea3.png">

**Comment by LaVLaS** [comment]
Closing this issues due to the age. If this is still an issue, please file open a new issue in https://github.com/opendatahub-io/opendatahub-community/issues
